name: Merge Release PR

on:
  pull_request_review:
    types: [submitted]

jobs:
  pr_approved:
    if: ${{ github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'next' }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone git repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Merge PR
        run: |
          git checkout main
          git merge --ff origin/next

      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main